### ISSUE TITLE
handleScalar() :: unsupported type (possibly rank  > 5?)

### ISSUE THREAD

**Issue by pburgos** [Goddard-Fortran-Ecosystem/pFlogger#7]
Using pFlogger from Master.
Trying to log an error message results in the following line in my logger file.

handleScalar() :: unsupported type (possibly rank  > 5?)

I tried error messages like the ones that appears in the examples. 

![image](https://user-images.githubusercontent.com/226372/61249603-ad052400-a723-11e9-9bfc-d837465917fa.png)

![image](https://user-images.githubusercontent.com/226372/61249695-eccc0b80-a723-11e9-9705-413454ee80cd.png)

**Comment by pburgos** [comment]
The problem was not in the code else in the examples.
I used configuration files from:
- pFlogger/examples/mpi/all_in_one.cfg
- pFlogger/examples/serial/all_in_one.cfg

In that examples the "formatters" are using `%(levelName)a`  as format string. That should be ` %(level_name)a` instead, as stated in pFlogger/src/FastFormatter.F90 . After that change, everything worked as expected.

**Comment by tclune** [comment]
@pburgos Thank you for spotting that, and my apologies for not having responded on this ticket sooner.   The issue was created just as I returned from vacation and am only now catching up on my open source projects.
