### ISSUE TITLE
Stray prints in pFlogger

### ISSUE THREAD

**Issue by mathomp4** [Goddard-Fortran-Ecosystem/pFlogger#74]
In running GEOS with MAPL3 I noticed some stray prints:
```
 Config.F90          87 F T           4
 Config.F90          89 T
 Config.F90          90 plain
 Config.F90          87 F T           4
 Config.F90          87 F T           4
...
```
After searching through MAPL and realizing they weren't in there, I figured it was a GFE library. And I think it's from this:

https://github.com/Goddard-Fortran-Ecosystem/pFlogger/blob/767421fc682d88c26828091ee4e861c2fa9834b5/src/Config.F90#L85-L92

I can make a PR (assuming these aren't needed), and I just need to know if I should hotfix or just put onto develop where there already is a bit of a "cleanup" change:

https://github.com/Goddard-Fortran-Ecosystem/pFlogger/compare/develop

**Comment by tclune** [comment]
Oops.   I guess technically it is a bug in that pFlogger is all about I/O and should not produce "extra".  So do a hot fix.
