### ISSUE TITLE
Change submodule to be https rather than ssh

### ISSUE THREAD

**Issue by mathomp4** [Goddard-Fortran-Ecosystem/pFlogger#8]
In trying to figure out how to build Baselibs with NVIDIA HPCCM, I'm trying to avoid ssh URLs in `.gitmodules` as much as possible. I converted Baselibs, but pFlogger currently uses:
https://github.com/Goddard-Fortran-Ecosystem/pFlogger/blob/52d7a35372d444bedf30f7af9a677d016c4f2a3f/.gitmodules#L1-L3

Could this be converted to https?

(Note: this can be done in git 2.25 (most recent release) with `git submodule set-url`. Which is how I did it with ESMA-Baselibs.

**Comment by tclune** [comment]
Yes.   Please create a PR.
